languages = [
    "Albanian",
    "American Sign Language",
    "Amharic",
    "Arabic",
    "Armenian",
    "Bulgarian",
    "Burmese",
    "Cambodian",
    "Cantonese",
    "Cebuano",
    "Croatian",
    "Czech",
    "Danish",
    "Dutch",
    "English",
    "Estonian",
    "Fijian",
    "Finnish",
    "French",
    "Georgian",
    "German",
    "Greek",
    "Haitian Creole",
    "Hiligaynon",
    "Hmong",
    "Hungarian",
    "Icelandic",
    "Indonesian",
    "Italian",
    "Japanese",
    "Kiribati",
    "Korean",
    "Lao",
    "Latvian",
    "Lithuanian",
    "Macedonian",
    "Malagasy",
    "Malay",
    "Mandarin (Traditional)",
    "Marshallese",
    "Mongolian",
    "Nepali",
    "Norwegian",
    "Persian",
    "Polish",
    "Portuguese",
    "Portuguese (Brazil)",
    "Quechua (Bolivian)",
    "Quechua (Peru)",
    "Romanian",
    "Russian",
    "Samoan",
    "Serbian",
    "Slovak",
    "Slovene",
    "Spanish",
    "Swahili",
    "Swedish",
    "Tagalog",
    "Tahitian",
    "Thai",
    "Tongan",
    "Turkish",
    "Ukrainian",
    "Vietnamese"
]

macrolanguages = [
    "Swahili",
    "Malay",
    "Nepali"
]

core_languages = [
    "Spanish",
    "Portuguese",
    "?"
]

non_core_languages = [
    
]